version: '3'
services:
  mini_project:
	  # image: naemyouimages
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3221:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
			- data_analytics
networks:
  data_analytics:
    external: true	   
 	