
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import NavbarComponent from "@/components/navbar/navbar";
import FooterComponent from "@/components/footer/footer";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph:{
    type:"website",
    url:"https://nextjs.org/",
    title:"Create Next App",
    description:"Generated by create next app",
    images:"https://nextjs.org/static/twitter-cards/home.jpg",
  },
  }
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=''>
       <header>
        <NavbarComponent/>
       </header>
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
