
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import NavbarComponent from "@/components/navbar/navbar";
import FooterComponent from "@/components/footer/footer";
import inter from "./fonts";
export const metadata: Metadata = {
  title: "Cambo Products",
  description: "Generated by create next app",
  openGraph:{
    type:"website",
    url:"https://istad.co",
    title:"Cambo Products",
    description:"Generated by create next app",
    images:"https://www.istad.co/resources/img/CSTAD_120.png",
  },
  }
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${inter.variable}`}>
       <header>
        <NavbarComponent/>
       </header>
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
